apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jaug

resources:
  - namespace.yaml
  - ../../../../apps/hello-dotnet/base

images:
  - name: hello-dotnet
    newName: mcr.microsoft.com/dotnet/samples
    newTag: aspnetapp-chiseled-9.0