apiVersion: v1
kind: Service
metadata:
  name: hello-dotnet
spec:
  type: LoadBalancer
  selector:
    app: hello-dotnet
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
