name: apps deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/setup-kubectl@v4

      - uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: "v0.1.4"

      - uses: azure/k8s-bake@v3
        with:
          renderEngine: kustomize
          kustomizationPath: ./gitops/clusters/development/aks-jaug/hello-dotnet
          kubectl-version: latest
        id: bake

      - uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AZURE_AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AZURE_AKS_CLUSTER_NAME }}
          admin: false
          use-kubelogin: true

      - uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          namespace: jaug
